import type { DemoStop } from "./DemoTourTypes";

export const demoStops: DemoStop[] = [
  {
    id: "survival",
    anchor: { x: 2.8, y: 2.1, z: -1.2 },
    camPos: { x: 8.5, y: 5.8, z: 8.8 },
    camLookAt: { x: 2.8, y: 1.8, z: -1.2 },
    title: "SURVIVAL OUTLOOK",
    headline: "62% likelihood of sustaining the next 24 months.",
    subline: "38% fall short without change.",
    arrow: "neutral",
    ai: {
      what: "Right now, the baseline has a 62% likelihood of sustaining the next 24 months.",
      why: "The downside cases are driven by a cash trough that arrives before revenue momentum fully stabilises.",
      means: "If nothing changes, more than a third of outcomes run out of room before scale.",
    },
  },
  {
    id: "cashValley",
    anchor: { x: -4.2, y: 0.2, z: 3.6 },
    camPos: { x: -10.5, y: 4.8, z: 10.2 },
    camLookAt: { x: -4.2, y: 0.4, z: 3.6 },
    title: "CASH VALLEY RISK",
    headline: "Lowest projected cash: Month 14.",
    subline: "Funding likely required before breakeven.",
    arrow: "down",
    ai: {
      what: "This valley is the lowest projected cash point — around month 14.",
      why: "In weaker runs, burn stays elevated while growth takes longer to compound.",
      means: "The timing window matters: funding is often required before breakeven.",
    },
  },
  {
    id: "growth",
    anchor: { x: 5.6, y: 1.7, z: 4.9 },
    camPos: { x: 12.2, y: 6.2, z: -2.0 },
    camLookAt: { x: 5.6, y: 1.6, z: 4.9 },
    title: "GROWTH TRAJECTORY",
    headline: "Scale achieved sustainably in 54% of simulations.",
    subline: "Volatility widens outcomes.",
    arrow: "up",
    ai: {
      what: "In 54% of simulations, growth reaches a sustainable path.",
      why: "The spread comes from demand variability and concentration effects that widen outcomes.",
      means: "The business can scale — but stability determines whether that scale is repeatable.",
    },
  },
  {
    id: "operating",
    anchor: { x: 0.8, y: 1.1, z: 6.5 },
    camPos: { x: 6.5, y: 4.9, z: -10.5 },
    camLookAt: { x: 0.8, y: 1.0, z: 6.5 },
    title: "OPERATING STABILITY",
    headline: "Margins compress in 41% of scenarios.",
    subline: "Small shocks materially affect runway.",
    arrow: "down",
    ai: {
      what: "Margins compress in 41% of scenarios.",
      why: "When costs are rigid, small shocks flow straight into runway.",
      means: "The risk here isn't just performance — it's sensitivity.",
    },
  },
  {
    id: "capital",
    anchor: { x: -6.4, y: 0.6, z: -3.9 },
    camPos: { x: -12.5, y: 5.3, z: 0.8 },
    camLookAt: { x: -6.4, y: 0.6, z: -3.9 },
    title: "CAPITAL PRESSURE",
    headline: "External funding required in 47% of scenarios.",
    subline: "Dependency increases under volatility.",
    arrow: "down",
    ai: {
      what: "External funding is required in 47% of scenarios.",
      why: "Volatility and timing push more runs into dependency.",
      means: "Capital isn't a plan — it's a pressure. Reducing dependency increases control.",
    },
  },
  {
    id: "value",
    anchor: { x: 3.5, y: 2.5, z: 2.0 },
    camPos: { x: 9.8, y: 6.0, z: 4.4 },
    camLookAt: { x: 3.5, y: 2.1, z: 2.0 },
    title: "VALUE BAND",
    headline: "Enterprise value range: $18m – $42m.",
    subline: "Value compresses rapidly under stress.",
    arrow: "neutral",
    ai: {
      what: "Across futures, enterprise value ranges from $18m to $42m.",
      why: "Value expands when survival holds and the growth ridge stabilises.",
      means: "Under stress, value compresses quickly — trajectory drives valuation, not assumptions.",
    },
  },
];
